//
// Created by Demon on 2024/5/15.
//

#ifndef DEMONENGINE_ANIMATIONVALUEDEFINE_HPP
#define DEMONENGINE_ANIMATIONVALUEDEFINE_HPP

#define MAX_BONES 100
#define MAX_BONE_INFLUENCE 4

#endif //DEMONENGINE_ANIMATIONVALUEDEFINE_HPP
